name: publish-release-to-twitter
on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: infraway/tweet-action@v1
        with:
          status: Signalrcore ${{ github.event.release.tag_name }} released, https://pypi.org/project/signalrcore/ #SignalR #AspNetCore #Python 
          api_key: ${{ secrets.TWITTER_API_KEY }}
          api_key_secret: ${{ secrets.TWITTER_API_KEY_SECRET }}
          access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
